# Generated by Django 3.2.14 on 2022-07-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, verbose_name='County Code')),
                ('coupon_id', models.IntegerField(verbose_name='Coupon Id')),
                ('coupon_webshop_name', models.CharField(max_length=150, verbose_name='Coupon Webshop Name')),
                ('description', models.TextField(verbose_name='description')),
                ('first_seen', models.DateField(verbose_name='First Seen')),
                ('last_seen', models.DateField(verbose_name='Last Seen')),
                ('promotion_type', models.CharField(max_length=20, verbose_name='Promotions Type')),
                ('title', models.CharField(max_length=200, verbose_name='Coupon Webshop Name')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('webshop_id', models.CharField(max_length=200, verbose_name='Webshop Id')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
