# Generated by Django 3.2.14 on 2022-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20220715_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='promotion_type',
            field=models.IntegerField(choices=[(100, 'percent-off,'), (200, 'buy-one-get-one'), (300, 'dollar-off'), (400, 'free-gift'), (500, 'free-shipping')], max_length=20, verbose_name='Promotions Type'),
        ),
    ]
