# Generated by Django 3.2.14 on 2022-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='promotion_type',
            field=models.CharField(choices=[('percent-off', 'percent-off'), ('buy-one-get-one', 'buy-one-get-one'), ('dollar-off', 'dollar-off'), ('free-gift', 'free-gift'), ('free-shipping', 'free-shipping')], max_length=20, verbose_name='Promotions Type'),
        ),
    ]
