# Generated by Django 3.2.14 on 2022-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_coupon_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(null=True, verbose_name='Value'),
        ),
    ]
